Bug/update instruments
LCOGT/calibration-tom pull request #49
Opened 2022-02-16 19:57 UTC by nvolgenau

These mods, tested on local Calibration-TOM, enabled photometric standard cadences to be started on MuSCAT. I've left in, but commented out, the print statements that I used to monitor program flow.

2022-02-16 21:57 UTC, jchate6 commented
It might make more sense to convert the commented `print()` statements into debug statements. 
An example can be seen on line 235.

2022-02-16 22:01 UTC, jchate6 commented
Another inconsistency, unrelated to this PR directly, but one that should probably be addressed is that the README includes the line `/opt/lcogt-python36/bin/python3.6 -m venv tom_env` which will install a venv with python3.6, but tomtoolkit requires python 3.7.

2022-02-16 22:02 UTC, jchate6 requested changes

2022-02-17 19:09 UTC, nvolgenau commented on requirements.txt
> +# to find local version of tom_base
Change made.

2022-02-17 19:26 UTC, jchate6 approved these changes

2022-02-18 18:28 UTC, merged